"""entries table

Revision ID: 8a659772d7f0
Revises: 8c412ca3aa42
Create Date: 2022-11-24 14:59:55.201362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a659772d7f0'
down_revision = '8c412ca3aa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bahnhof', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('beschreibung', sa.String(length=120), nullable=False))
        batch_op.drop_index('ix_entry_description')
        batch_op.drop_index('ix_entry_title')
        batch_op.create_index(batch_op.f('ix_entry_bahnhof'), ['bahnhof'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_beschreibung'), ['beschreibung'], unique=False)
        batch_op.drop_column('title')
        batch_op.drop_column('description')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_entry_beschreibung'))
        batch_op.drop_index(batch_op.f('ix_entry_bahnhof'))
        batch_op.create_index('ix_entry_title', ['title'], unique=False)
        batch_op.create_index('ix_entry_description', ['description'], unique=False)
        batch_op.drop_column('beschreibung')
        batch_op.drop_column('bahnhof')

    # ### end Alembic commands ###
