"""entries table

Revision ID: 8c412ca3aa42
Revises: 728b69241202
Create Date: 2022-11-24 14:00:10.035880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c412ca3aa42'
down_revision = '728b69241202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_title'))
        batch_op.drop_index(batch_op.f('ix_entry_description'))

    op.drop_table('entry')
    # ### end Alembic commands ###
